name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF_B64 }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Download build artifact from Google Drive
        run: |
          rclone copy gdrive:ci-builds/ecommerce/dist.zip ./dist.zip --progress

      - name: Unzip into Nginx html folder
        run: |
          unzip -o dist.zip -d /home/smalllab/Docker/ecommerce/nginx/html
