name: CI Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    types: ["closed"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p /home/runner/.config/rclone
          echo "${{ secrets.RCLONE_CONF_B64 }}" | base64 -d > /home/runner/.config/rclone/rclone.conf

      - name: Upload to Google Drive
        run: |
          rclone copy ./dist gdrive:ci-builds/ecommerce --progress
